CREATE USER 'kiwi_dev'@'%' IDENTIFIED BY 'MS6h2Ym4L^y4T!f$';

GRANT ALL PRIVILEGES ON *.* TO 'kiwi_dev'@'%';

flush privileges;

CREATE DATABASE IF NOT EXISTS kiwi DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

USE kiwi;

CREATE TABLE IF NOT EXISTS kiwi_categories (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    name VARCHAR(200) NOT NULL ,
    father_id INT DEFAULT 0 COMMENT '父级ID,默认为0',
    level INT DEFAULT 1 COMMENT '第几级分类',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_brand (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  c_id INT UNSIGNED NOT NULL COMMENT '分类ID',
  name VARCHAR(200) NOT NULL ,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT 0 ,
  FOREIGN KEY (c_id) REFERENCES kiwi_categories(id) ON UPDATE CASCADE ON DELETE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_goods (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    c_id INT UNSIGNED NOT NULL COMMENT '分类ID',
    b_id INT UNSIGNED DEFAULT 0 COMMENT '品牌ID',
    show_title VARCHAR(200) UNIQUE NOT NULL COMMENT '显示的标题',
    name VARCHAR(200) NOT NULL COMMENT '商品名称',
    producing_area VARCHAR(200) NOT NULL COMMENT '产地',
    unit VARCHAR(50) NOT NULL COMMENT '规矩,一箱(6个装)!一件!或是一个',
    stock_num INT UNSIGNED NOT NULL COMMENT '库存数量',
    illustrate VARCHAR(255) COMMENT '详细介绍',
    now_price INT NOT NULL COMMENT '现价',
    out_price INT NOT NULL COMMENT '售价',
    in_price INT DEFAULT 0 COMMENT '进价',
    status TINYINT(1) DEFAULT 0 COMMENT '1:上架 , 0:下架',
    on_off_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '上架或下架的时间',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT 0 ,
    FOREIGN KEY (c_id) REFERENCES kiwi_categories(id) ON UPDATE CASCADE ON DELETE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_goods_imgs (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    g_id INT UNSIGNED NOT NULL,
    img_url VARCHAR(255) NOT NULL COMMENT '图片地址',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT 0,
    FOREIGN KEY(g_id) REFERENCES kiwi_goods(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    nick_name VARCHAR(200) NOT NULL ,
    account VARCHAR(11) NOT NULL COMMENT '登录帐号为手机号',
    password VARCHAR(32) NOT NULL ,
    salt VARCHAR(16) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_user_address (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    u_id INT UNSIGNED NOT NULL COMMENT '用户ID',
    province VARCHAR(16) NOT NULL COMMENT '省',
    city VARCHAR(16) NOT NULL COMMENT '市',
    district VARCHAR(16) NOT NULL COMMENT '区',
    address VARCHAR(200) NOT NULL COMMENT '详细地址',
    house_number VARCHAR(200) NOT NULL COMMENT '门牌号',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT 0 ,
    FOREIGN KEY(u_id) REFERENCES kiwi_users(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_carts (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    u_id INT UNSIGNED NOT NULL COMMENT '用户ID',
    g_id INT UNSIGNED NOT NULL COMMENT '商品ID',
    c_id INT UNSIGNED NOT NULL COMMENT '分类ID',
    b_id INT UNSIGNED DEFAULT 0 COMMENT '品牌ID',
    b_name VARCHAR(200) COMMENT '品牌名称',
    show_title VARCHAR(200) NOT NULL COMMENT '显示的标题',
    name VARCHAR(200) NOT NULL COMMENT '商品名称',
    producing_area VARCHAR(200) NOT NULL COMMENT '产地',
    unit VARCHAR(50) NOT NULL COMMENT '规矩,一箱(6个装)!一件!或是一个',
    now_price INT NOT NULL COMMENT '现价',
    buy_num INT NOT NULL DEFAULT 0 COMMENT '购买数量',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT 0,
    FOREIGN KEY(g_id) REFERENCES kiwi_goods(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(u_id) REFERENCES kiwi_users(id) ON UPDATE CASCADE ON DELETE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_orders (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    order_num VARCHAR(32) NOT NULL COMMENT '订单号',
    service_charge INT DEFAULT 0 COMMENT '服务费、配送费',
    g_total_price INT NOT NULL COMMENT '商品总价',
    pay_total INT NOT NULL COMMENT '总共需支付的总价',
    status INT DEFAULT 1 COMMENT '订单状态',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_order_address (
    o_id INT UNSIGNED NOT NULL PRIMARY KEY ,
    province VARCHAR(16) NOT NULL COMMENT '省',
    city VARCHAR(16) NOT NULL COMMENT '市',
    district VARCHAR(16) NOT NULL COMMENT '区',
    address VARCHAR(200) NOT NULL COMMENT '详细地址',
    house_number VARCHAR(200) NOT NULL COMMENT '门牌号',
    FOREIGN KEY(o_id) REFERENCES kiwi_orders(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS kiwi_order_infos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    o_id INT UNSIGNED NOT NULL COMMENT '订单ID',
    u_id INT UNSIGNED NOT NULL COMMENT '用户ID',
    g_id INT UNSIGNED NOT NULL COMMENT '商品ID',
    c_id INT UNSIGNED NOT NULL COMMENT '分类ID',
    b_id INT UNSIGNED DEFAULT 0 COMMENT '品牌ID',
    b_name VARCHAR(200) COMMENT '品牌名称',
    show_title VARCHAR(200) NOT NULL COMMENT '显示的标题',
    name VARCHAR(200) NOT NULL COMMENT '商品名称',
    producing_area VARCHAR(200) NOT NULL COMMENT '产地',
    unit VARCHAR(50) NOT NULL COMMENT '规矩,一箱(6个装)!一件!或是一个',
    now_price INT NOT NULL COMMENT '现价',
    buy_num INT NOT NULL DEFAULT 0 COMMENT '购买数量',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT 0,
    FOREIGN KEY(g_id) REFERENCES kiwi_goods(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(u_id) REFERENCES kiwi_users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(o_id) REFERENCES kiwi_orders(id) ON UPDATE CASCADE ON DELETE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;